language: php

matrix:
  include:
    - php: 7.2
      env: LARAVEL_VERSION="5.8.*" ORCHESTRA_VERSION="3.8.*"
    - php: 7.2
      env: LARAVEL_VERSION="6.*" ORCHESTRA_VERSION="4.0.*"
    - php: 7.3
      env: LARAVEL_VERSION="5.8.*" ORCHESTRA_VERSION="3.8.*"
    - php: 7.3
      env: LARAVEL_VERSION="6.*" ORCHESTRA_VERSION="4.0.*"
    - php: 7.4
      env: LARAVEL_VERSION="5.8.*" ORCHESTRA_VERSION="3.8.*"
    - php: 7.4
      env: LARAVEL_VERSION="6.*" ORCHESTRA_VERSION="4.0.*"
cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - composer require "laravel/framework:${LARAVEL_VERSION}" --no-update
  - composer require "orchestra/testbench:${ORCHESTRA_VERSION}" --no-update

install: composer update
